# LLM Endpoint Settings

chunk_size: 34
threads: 5 # Number of threads for parallel processing
rate_limit: 30 # requests per minute
max_chars: 132
max_duration: 10.0

summary_model:
  type: "gemini"
  api_key: "AIzaSyB6oJzXNb9ZhfI8-NBwpDQZi6VwFJmKqW8"
  model: "gemini-3.1-flash-lite-preview"
  max_tokens: 8192
  temperature: 0.5
  top_p: 0.85
  top_k: 12
  frequency_penalty: 0.0
  presence_penalty: 0.0

# Deepseek
translation_model_2:
  type: "openai"
  endpoint: "https://api.deepseek.com"
  api_key: "sk-4a40e2a65158440fb7cd54d71acc60b1"
  model: "deepseek-chat"
  max_tokens: 2048
  temperature: 0.6
  top_p: 0.85
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stream: false

translation_model:
  type: "gemini"
  api_key: "AIzaSyB6oJzXNb9ZhfI8-NBwpDQZi6VwFJmKqW8"
  model: "gemini-3.1-flash-lite-preview"
  max_tokens: 8192
  temperature: 0.8
  top_p: 0.85
  top_k: 12
  frequency_penalty: 0.0
  presence_penalty: 0.0
  rate_limit: 15 # requests per minute

asr:
  model: "Qwen/Qwen3-ASR-1.7B"
  forced_aligner: "Qwen/Qwen3-ForcedAligner-0.6B"
  max_audio_length: 300
  device: "cpu"
