# LLM Endpoint Settings

summary_model:
  type: "openai"
  endpoint: "https://api.deepbricks.ai/v1"
  api_key: "sk-71vszCdxPZ5YWupqw37AkfAxjcMkAxB4BQgqDjlv16716MIX"
  model: "gpt-4o-mini"
  max_tokens: 8192
  temperature: 0.6
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0

translation_model_1:
  type: "custom"
  endpoint: "https://api.siliconflow.cn/v1"
  api_key: "sk-wofhvszkzdscfbbcqgdktuiyyjdkycxxklcsjcefqposywms"
  model: "deepseek-ai/DeepSeek-V2.5"
  max_tokens: 512
  temperature: 0.6
  top_p: 0.7
  top_k: 20
  frequency_penalty: 0.5
  n: 1
  stream: false

chunk_size: 14
threads: 40 # Number of threads for parallel processing
max_chars: 68
max_duration: 7.0

# Deepseek
translation_model:
  type: "openai"
  endpoint: "https://api.deepseek.com"
  api_key: "sk-4a40e2a65158440fb7cd54d71acc60b1"
  model: "deepseek-chat"
  max_tokens: 1024
  temperature: 0.6
  top_p: 0.7
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stream: false

translation_model_3:
  type: "openai"
  endpoint: "https://api.deepbricks.ai/v1"
  api_key: "sk-71vszCdxPZ5YWupqw37AkfAxjcMkAxB4BQgqDjlv16716MIX"
  model: "gpt-4o-mini"
  max_tokens: 1024
  temperature: 0.6
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stream: false